/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    colors: {
      'black': '#000000',
      'white': '#f8fafc',
      'agencyGray': 'rgb(212 212 212)',
      'agencyMidGray': 'rgba(255, 255, 255, 0.5)',
      'agencyButton': 'rgba(248, 170, 14, 1)',
      'businessText': '#F5BD00',
      'businessTextHovered': '#F9B40B',
      'businessTextDefault': 'rgba(0, 0, 0, 0.25)',
      'businessCtaBox': 'rgba(203, 203, 203, 0.5)',
      'businessCtaBoxTwo': 'rgba(248, 248, 248, 1)',
      'businessCtaButton': '#353D46',
      'urbanHighlight': 'rgba(23, 22, 55, 1)',
      'urbanSubHighlight': 'rgba(53, 61, 70, 1)',
      'urbanTopSubText': 'rgba(136, 22, 59, 1)',
      'urbanGray': '#F3F3F3',
      'urbanTextMarker': '#89163B',
      'pageActive': 'rgba(249, 180, 11, 1)',
      'footerInput': 'rgba(245, 245, 245, 1)',
      'footerSubmit': 'rgba(137, 22, 59, 1)',
      'agencyOrange': 'rgba(221, 145, 26, 1)',
      'indexOrange': 'rgba(245, 189, 0, 1)',
      'footerBlue': 'rgba(32, 45, 63, 1)',
    },
    screens: {
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
    },
    extend: {
      fontFamily: {
        pushpenny:["pushpenny"],
        pushpennyBold:["pushpenny-bold"],    
        pushpennyLight:["pushpenny-light"],    
        pushpennyMedium:["pushpenny-medium"],    
        pushpennyXbold:["pushpenny-xbold"],    
      },
      height: {
        '120':'56rem',
        'midsection':'45rem',
        'heroMobile':'25rem',
        'heroTab':'35rem',
        'tenth':'10%',
        'ninth':'90%',
        'fourth':'40%',
        'quarter':'25%',
        'half':'50%',
        'midh':'328px',
        'baseh':'1859px',
        'base-man-sitting':'561px',
        'base-section-button':'40px',
        'footer-height':'260px',
        'menuImageHieght':'578px',
        'agencyTop':'1298px',
        'agencyBottom':'1859px',
        'midIndexOne':'10rem',
        'midIndexTwo':'3.1rem',
        'midTextOne':'3rem',
        'midIndexThree':'9.2rem',
        'businessTextMarker':'1.5rem',
        'businessHighlight':'15rem',
        'businessSubHighlight':'2.5rem',
        'businessMidSectionSubText':'5.5rem',
        'businessMidSectionSubTextTwo':'5.5rem',
        'businessMidSectionSubTextThree':'10.8rem',
        'businessMidSectionImage':'45.31rem',
        'urbanHighlightText':'22.13rem',
        'urbanTopText':'4.5rem',
        'urbanTopSubText':'3.6rem',
        'urbanMidSection':'74.5rem',
        'urbanMidSectionHeading':'13.12rem',
        'urbanCollage':'48.25rem',
        'urbanCollageMobile':'58.25rem',
        'urbanCta':'4.5rem',
        'urbanCtaDesc':'5rem',
        'footerDetails':'13.25rem',
        'agencyMidHeading':'18.87rem',
        'agencyMidPic':'33.8rem',
        'logo':'104px',
        'lgh':'218px',
  
        
      },
      width: {
        'lgw':'174px',
        'tenth':'10%',
        'logo':'296px',
        'ninth':'90%',
        'nineFifth':'95%',
        'quarter':'25%',
        'fourth':'40%',
        'half':'50%',
        'midw':'264px',
        'third':'33.3%',
        'tenthmore':'110%',
        'quartermore':'120%',
        'base-man-sitting':'561px',
        'base-section-button':'136px',
        'menuImageWidth':'402px',
        'midIndexOne':'16rem',
        'midIndexTwo':'16rem',
        'midTextOne':'11.5rem',
        'midIndexThree':'19rem',
        'businessTextMarker':'1.5rem',
        'businessHighlight':'68rem',
        'businessSubHighlight':'30rem',
        'businessMidSectionText':'26rem',
        'businessMidSectionSubText':'19.6rem',
        'footerCta':'18.6rem',
        'businessMidSectionSubTextTwo':'21.6rem',
        'businessMidSectionSubTextThree':'20.68rem',
        'businessMidSectionImage':'30.31rem',
        'businessCta':'28rem',
        'urbanHighlightText':'70.25rem',
        'urbanTopText':'33.8rem',
        'urbanMidSection':'77.5rem',
        'urbanMidSectionHeading':'37.75rem',
        'urbanMidSubSection':'32rem',
        'urbanMidSubSectionTwo':'27.87rem',
        'urbanCollage':'28.50rem',
        'urbanCta':'21rem',
        'footerDetails':'14rem',
        'footerSubmit':'7.2rem',
        'agencyMidPic':'33.3rem',
        'indexDesc':'499px',
      },
      margin: {
        'whole':'700px',
        'outBox':'500px',
      },
      fontSize: {
        'tiny':['10px'],
        'smaller':['13px'],
        'indexsmaller':['14px'],
        'small':['18px'],
        'urbanMid':['20px'],
        'mid':['24px'],
        'big':['37px'],
        'urbanBig':['64px'],
        'bigger':['120px'],
        'hero-highlight':['140px'],
      },
      lineHeight: {
        'urbanHighlight': '118px',
        'urbanMidSectionHeading': '75px',
        'urbanCta': '35px',
        'urbanCtaDesc': '20px',
        'indexSmall': '23px',
        'indexMidSection': '31px',
        'agencyMid': '24px',
        'indexMid': '64px',
      },
      padding: {
        'tenth':'10%',
      },
      borderRadius: {
        'first':'8px',
        'second':'12px',
        'third':'14px',
      },
      backgroundImage: {
        'hero-pattern':"url('/images/hero.png')",
        'hero-pattern-pic-1':"url('/images/hero-section-left/home-image-one.png')",
        'hero-pattern-pic-2':"url('/images/hero-section-right/home-image-two.png')",
        'mid-section-heading':"url('/images/mid-section/mid-section-heading.svg')",
        'mid-section-divider':"url('/images/mid-section/mid-section-divider.svg')",
        'mid-section-image-one':"url('/images/index-page/index-pos.png')",
        'mid-section-image-two':"url('/images/mid-section/mid-second-image.png')",
        'mid-section-image-three':"url('/images/mid-section/mid-third-image.png')",
        'base-section-background':"url('/images/base-section/base-section-background.svg')",
        'man-sitting':"url('/images/index-page/man-sitting.png')",
        'base-section-button':"url('/images/base-section/buttons.svg')",
        'logo':"url('/images/logo.svg')",
        'midIndexOne':"url('/images/mid-section/image-one-text.svg')",
        'midIndexTwo':"url('/images/mid-section/image-two-text.svg')",
        'midIndexThree':"url('/images/mid-section/with-payrail.svg')",
        'businessTextMarker':"url('/images/business-page/business-text-marker.svg')",
        'businessHeading':"url('/images/business-page/business-page-header.png')",
        'businessHighlight':"url('/images/business-page/business-highlight-text.png')",
        'businessSubHighlight':"url('/images/business-page/business-subhighlight-text.png')",
        'businessMidsectionPattern':"url('/images/business-page/business-page-midsection-pattern.png')",
        'businessMidPattern':"url('/images/business-page/business-midsection-pattern.png')",
        'businessCta':"url('/images/business-page/business-page-cta.png')",
        'urbanPhone':"url('/images/urban-page/urban-phone.png')",
        'urbanCollage':"url('/images/urban-page/urban-collage.png')",
        'midTextOne':"url('/images/mid-section/mid-section-first.png')",
      },     
      keyframes: {
        leftTransitionIn: {
          '0%': {marginLeft:'-1060px'},
          '100%': {marginLeft:'0px'},
        },
        rightTransitionIn: {
          '0%': {marginLeft:'2000px'},
          '100%': {marginLeft:'0px'},
        },
        topTransitionIn: {
          '0%': {marginTop:'-700px'},
          '100%': {marginTop:'160px'},
        },
        bottomTransitionIn: {
          '0%': {marginTop:'3000px'},
          '100%': {marginTop:'0px'},
        },
        menuTransition: {
          '0%': {opacity:'0'},
          '100%': {opacity:'1'},
        },
      },
      animation:{
        menuTransition: 'menuTransition 0.5s linear',
        menuTransitionTwo: 'menuTransition 0.8s linear',
        menuTransitionThree: 'menuTransition 1.1s linear',
        menuTransitionFour: 'menuTransition 1.2s linear',
        menuTransitionFive: 'menuTransition 1.4s linear',
      },
    },
  },
  plugins: [],
}
